Repository cozy/create-cozy-app, pull requests merged in 2018-02, with the labels that each got.

#279 Throw error in build instead of (log + return) + enable `bail` for build script
  packages/cozy-scripts/scripts/build.js
Labels: tag: enhancement

#280 Compute `manifest.webapp` locales/langs from `manifest` property in src/locales
  packages/babel-preset-cozy-app/README.md
  packages/cozy-scripts/config/webpack.config.manifest.js
  packages/cozy-scripts/docs/webpack-configs.md
  packages/cozy-scripts/utils/paths.js
Labels: tag: feature

#281 Better polyfills usage for ie11 `Object.assign` support
  packages/babel-preset-cozy-app/index.js
Labels: tag: enhancement

#290 Use correctly the environment variable in manifest config
  packages/cozy-scripts/config/webpack.config.manifest.js
Labels: tag: bug

#291 Console log the used environment and target when compiling
  packages/cozy-scripts/config/webpack.vars.js
Labels: tag: enhancement

#320 Add lerna postinstall script in the root package.json
  package.json
Labels: tag: chore

#311 feat: add root in image path in webpack config ✨
  packages/cozy-scripts/config/webpack.config.pictures.js
  packages/cozy-scripts/test/__snapshots__/scripts-vue.spec.js.snap
  packages/cozy-scripts/test/__snapshots__/scripts.spec.js.snap
Labels: tag: bug

#296 Eslint improvements
  packages/cozy-scripts/config/webpack.config.eslint.js
  packages/cozy-scripts/test/__snapshots__/scripts-vue.spec.js.snap
  packages/cozy-scripts/test/__snapshots__/scripts.spec.js.snap
Labels: tag: enhancement

#326 Remove `.gitignore` in package.json files property
  packages/cozy-scripts/package.json
Labels: tag: chore

#327 Remove npm slug and description CLI questions
  packages/cozy-scripts-vanilla/scripts/init.js
  packages/cozy-scripts-vanilla/template/README.md
  packages/cozy-scripts-vanilla/test/scripts.spec.js
  packages/cozy-scripts/scripts/init.js
  packages/cozy-scripts/template-vue/README.md
  packages/cozy-scripts/template-vue/manifest.webapp
  packages/cozy-scripts/template/README.md
  packages/cozy-scripts/template/manifest.webapp
  packages/cozy-scripts/test/scripts-vue.spec.js
  packages/cozy-scripts/test/scripts.spec.js
Labels: tag: enhancement

#328 Remove category question and use `categories` array
  packages/cozy-scripts-vanilla/scripts/init.js
  packages/cozy-scripts-vanilla/template/manifest.webapp
  packages/cozy-scripts-vanilla/test/scripts.spec.js
  packages/cozy-scripts/scripts/init.js
  packages/cozy-scripts/template-vue/manifest.webapp
  packages/cozy-scripts/template/manifest.webapp
  packages/cozy-scripts/test/scripts-vue.spec.js
  packages/cozy-scripts/test/scripts.spec.js
Labels: tag: enhancement

#329 Handle app slug with a CLI question
  packages/cozy-scripts-vanilla/scripts/init.js
  packages/cozy-scripts-vanilla/template/manifest.webapp
  packages/cozy-scripts-vanilla/test/scripts.spec.js
  packages/cozy-scripts/scripts/init.js
  packages/cozy-scripts/template/manifest.webapp
  packages/cozy-scripts/test/scripts-vue.spec.js
  packages/cozy-scripts/test/scripts.spec.js
Labels: tag: enhancement
