Repository cozy/create-cozy-app, pull requests merged in 2018-10, with the labels that each got.

#837 Global improvements/fixes
  README.md
  packages/cozy-scripts/README.md
  packages/cozy-scripts/bin/cozy-scripts.js
  packages/cozy-scripts/config/webpack.config.eslint.js
  packages/cozy-scripts/config/webpack.config.manifest.js
  packages/cozy-scripts/config/webpack.config.services.js
  packages/cozy-scripts/docs/toc.yaml
  packages/cozy-scripts/docs/webpack-configs.md
  packages/cozy-scripts/scripts/start.js
  packages/cozy-scripts/template-vue/package.json
  packages/cozy-scripts/template/package.json
  packages/cozy-scripts/test/__snapshots__/scripts-vue.spec.js.snap
  packages/cozy-scripts/test/__snapshots__/scripts.spec.js.snap
  packages/create-cozy-app/README.md
Labels: tag: enhancement

#838 Minor doc changes
  README.md
  packages/create-cozy-app/README.md
Labels: tag: documentation

#840 Fix: Exiting the script stops docker correctly
  packages/cozy-scripts/scripts/start.js
Labels: tag: bug

#841 Add missing postcss-discard-empty dependency
  packages/cozy-scripts/package.json
Labels: tag: bug

#853 Always write files on dev mode
  packages/cozy-scripts/config/webpack.environment.dev.js
  packages/cozy-scripts/test/__snapshots__/scripts-vue.spec.js.snap
  packages/cozy-scripts/test/__snapshots__/scripts.spec.js.snap
Labels: tag: bug

#857 Add `USE_REACT` env variable for cozy-ui
  packages/cozy-scripts/config/webpack.config.react.js
  packages/cozy-scripts/test/__snapshots__/scripts.spec.js.snap
Labels: tag: enhancement

#893 Use writeToDisk intead of webpack plugin
  packages/cozy-scripts/config/webpack.environment.dev.js
  packages/cozy-scripts/package.json
  packages/cozy-scripts/scripts/start.js
  packages/cozy-scripts/test/__snapshots__/scripts-vue.spec.js.snap
  packages/cozy-scripts/test/__snapshots__/scripts.spec.js.snap
  packages/cozy-scripts/yarn.lock
Labels: tag: chore
