Repository cozy/create-cozy-app, pull requests merged in 2018-12, with the labels that each got.

#949 Add more expected filenames for init error handling
  packages/cozy-scripts/scripts/init.js
Labels: tag: enhancement

#938 Use the correct folder name in finish logs
  packages/cozy-scripts/scripts/init.js
Labels: tag: enhancement

#950 Add `cs` CLI alias and CLI tests + improve CLI
  .gitignore
  package.json
  packages/cozy-scripts/bin/cozy-scripts.js
  packages/cozy-scripts/package.json
  packages/cozy-scripts/scripts/lint.js
  packages/cozy-scripts/template-vue/package.json
  packages/cozy-scripts/template/package.json
  packages/cozy-scripts/test/__snapshots__/cli.spec.js.snap
  packages/cozy-scripts/test/cli.spec.js
  packages/cozy-scripts/yarn.lock
Labels: tag: enhancement

#952 Use paths as functions + handle more CLI path options
  packages/cozy-scripts/README.md
  packages/cozy-scripts/bin/cozy-scripts.js
  packages/cozy-scripts/config/webpack.config.base.js
  packages/cozy-scripts/config/webpack.config.cozy-ui.js
  packages/cozy-scripts/config/webpack.config.cozy-ui.react.js
  packages/cozy-scripts/config/webpack.config.hash.js
  packages/cozy-scripts/config/webpack.config.intents.js
  packages/cozy-scripts/config/webpack.config.manifest.js
  packages/cozy-scripts/config/webpack.config.services.js
  packages/cozy-scripts/config/webpack.config.vendors.js
  packages/cozy-scripts/config/webpack.environment.dev.js
  packages/cozy-scripts/config/webpack.target.browser.js
  packages/cozy-scripts/config/webpack.target.mobile.js
  packages/cozy-scripts/config/webpack.vars.js
  packages/cozy-scripts/scripts/lint.js
  packages/cozy-scripts/scripts/start.js
  packages/cozy-scripts/test/__snapshots__/cli.spec.js.snap
  packages/cozy-scripts/test/cli.spec.js
  packages/cozy-scripts/utils/cleanBuild.js
  packages/cozy-scripts/utils/paths.js
Labels: tag: feature

#954 Better environment variables handling code and paths testing
  .travis.yml
  package.json
  packages/cozy-scripts/bin/cozy-scripts.js
  packages/cozy-scripts/config/webpack.config.preact.js
  packages/cozy-scripts/config/webpack.config.react.js
  packages/cozy-scripts/config/webpack.config.vue.js
  packages/cozy-scripts/config/webpack.target.browser.js
  packages/cozy-scripts/config/webpack.vars.js
  packages/cozy-scripts/scripts/build.js
  packages/cozy-scripts/scripts/config.js
  packages/cozy-scripts/scripts/publish.js
  packages/cozy-scripts/scripts/release.js
  packages/cozy-scripts/scripts/start.js
  packages/cozy-scripts/scripts/watch.js
  packages/cozy-scripts/test/__snapshots__/cli.spec.js.snap
  packages/cozy-scripts/test/__snapshots__/scripts-vue.spec.js.snap
  packages/cozy-scripts/test/__snapshots__/scripts.spec.js.snap
  packages/cozy-scripts/test/__snapshots__/utils.spec.js.snap
  packages/cozy-scripts/test/cli.spec.js
  packages/cozy-scripts/test/scripts-vue.spec.js
  packages/cozy-scripts/test/scripts.spec.js
  packages/cozy-scripts/test/utils.spec.js
  packages/cozy-scripts/utils/constants.js
  packages/cozy-scripts/utils/paths.js
Labels: tag: chore

#982 Use only one vendors chunk
  packages/cozy-scripts/config/webpack.config.chunks.js
  packages/cozy-scripts/config/webpack.config.intents.js
  packages/cozy-scripts/config/webpack.target.browser.js
  packages/cozy-scripts/config/webpack.target.mobile.js
  packages/cozy-scripts/test/__snapshots__/scripts-vue.spec.js.snap
  packages/cozy-scripts/test/__snapshots__/scripts.spec.js.snap
Labels: tag: enhancement

#984 Handling application public page if exists
  packages/cozy-scripts/config/webpack.bundle.default.js
  packages/cozy-scripts/config/webpack.bundle.preact.js
  packages/cozy-scripts/config/webpack.bundle.vue.js
  packages/cozy-scripts/config/webpack.config.public.js
  packages/cozy-scripts/test/__snapshots__/utils.spec.js.snap
  packages/cozy-scripts/utils/paths.js
Labels: tag: feature

#981 feat: Added loader for font files
  packages/cozy-scripts/config/webpack.config.base.js
  packages/cozy-scripts/test/__snapshots__/scripts-vue.spec.js.snap
  packages/cozy-scripts/test/__snapshots__/scripts.spec.js.snap
Labels: tag: enhancement

#991 feat: BREAKING CHANGE don't auto-inject mobile chunks (mobile target only)
  packages/cozy-scripts/config/webpack.target.mobile.js
  packages/cozy-scripts/test/__snapshots__/scripts-vue.spec.js.snap
  packages/cozy-scripts/test/__snapshots__/scripts.spec.js.snap
Labels: tag: breaking change

#1014 Downgrade to DevServer 3.1.10 to avoid host checking bug
  packages/cozy-scripts/package.json
  packages/cozy-scripts/yarn.lock
Labels: tag: bug

#1013 Build intents and public chunks in specific folders
  packages/cozy-scripts/config/webpack.config.chunks.js
  packages/cozy-scripts/config/webpack.config.intents.js
  packages/cozy-scripts/config/webpack.config.public.js
  packages/cozy-scripts/config/webpack.vars.js
  packages/cozy-scripts/test/__snapshots__/scripts-vue.spec.js.snap
  packages/cozy-scripts/test/__snapshots__/scripts.spec.js.snap
Labels: tag: bug

#1015 Better handling public assets
  packages/cozy-scripts/config/webpack.config.pictures.js
  packages/cozy-scripts/test/__snapshots__/scripts-vue.spec.js.snap
  packages/cozy-scripts/test/__snapshots__/scripts.spec.js.snap
Labels: tag: enhancement
