Repository cozy/create-cozy-app, pull requests merged in 2018-09, with the labels that each got.

#752 Add better command description for cozy-scripts
  packages/cozy-scripts/bin/cozy-scripts.js
Labels: tag: enhancement

#771 Fix cozy-bar CSS in dev environment
  packages/cozy-scripts/config/webpack.environment.dev.js
  packages/cozy-scripts/docs/webpack-configs.md
  packages/cozy-scripts/package.json
  packages/cozy-scripts/test/__snapshots__/scripts-vue.spec.js.snap
  packages/cozy-scripts/test/__snapshots__/scripts.spec.js.snap
  packages/cozy-scripts/yarn.lock
Labels: tag: bug

#753 Add new cozy-scripts `release` CLI
  packages/cozy-scripts/README.md
  packages/cozy-scripts/bin/cozy-scripts.js
  packages/cozy-scripts/scripts/release.js
  packages/cozy-scripts/test/scripts-vue.spec.js
  packages/cozy-scripts/test/scripts.spec.js
Labels: tag: feature

#790 Development config improvements
  packages/cozy-scripts/config/webpack.config.eslint.js
  packages/cozy-scripts/config/webpack.environment.dev.js
  packages/cozy-scripts/docs/webpack-configs.md
  packages/cozy-scripts/test/__snapshots__/scripts-vue.spec.js.snap
  packages/cozy-scripts/test/__snapshots__/scripts.spec.js.snap
Labels: tag: enhancement

#791 Revert "chore(deps): update dependency cozy-client to v2.21.1"
  packages/cozy-scripts/template/package.json
  packages/cozy-scripts/template/yarn.lock
Labels: tag: up(deps)

#802 Add --fix on cozy-scripts
  README.md
  packages/cozy-scripts/README.md
  packages/cozy-scripts/bin/cozy-scripts.js
  packages/cozy-scripts/config/webpack.config.eslint.js
  packages/cozy-scripts/config/webpack.config.services.js
  packages/cozy-scripts/config/webpack.vars.js
  packages/cozy-scripts/test/__snapshots__/scripts-vue.spec.js.snap
  packages/cozy-scripts/test/__snapshots__/scripts.spec.js.snap
Labels: tag: enhancement

#809 Add `stack:nocsp` app script for HMR
  packages/cozy-scripts/package.json
  packages/cozy-scripts/stack/disableCSP.yaml
  packages/cozy-scripts/template-vue/package.json
  packages/cozy-scripts/template/package.json
Labels: tag: enhancement

#822 Make debug option set debug env variable
  packages/cozy-scripts/bin/cozy-scripts.js
Labels: tag: bug

#825 Minor documentation improvements
  packages/cozy-scripts-vanilla/README.md
  packages/cozy-scripts/scripts/init.js
Labels: tag: documentation

#826 Update html files for new stack variables
  packages/cozy-scripts-vanilla/template/index.html
  packages/cozy-scripts-vanilla/template/view2.html
  packages/cozy-scripts/template-vue/app/src/targets/browser/index.ejs
  packages/cozy-scripts/template/app/src/targets/browser/index.ejs
Labels: tag: enhancement

#827 Add eslint (cozy-app) and run it everywhere
  .eslintrc.json
  .travis.yml
  package.json
  packages/cozy-scripts-vanilla/scripts/init.js
  packages/cozy-scripts-vanilla/template/app/scripts/init.js
  packages/cozy-scripts-vanilla/test/scripts.spec.js
  packages/cozy-scripts/bin/cozy-scripts.js
  packages/cozy-scripts/config/webpack.bundle.default.js
  packages/cozy-scripts/config/webpack.bundle.preact.js
  packages/cozy-scripts/config/webpack.bundle.vue.js
  packages/cozy-scripts/config/webpack.config.analyzer.js
  packages/cozy-scripts/config/webpack.config.base.js
  packages/cozy-scripts/config/webpack.config.cozy-ui.js
  packages/cozy-scripts/config/webpack.config.cozy-ui.react.js
  packages/cozy-scripts/config/webpack.config.css-modules.js
  packages/cozy-scripts/config/webpack.config.hash.js
  packages/cozy-scripts/config/webpack.config.intents.js
  packages/cozy-scripts/config/webpack.config.manifest.js
  packages/cozy-scripts/config/webpack.config.progress.js
  packages/cozy-scripts/config/webpack.config.services.js
  packages/cozy-scripts/config/webpack.config.vue.js
  packages/cozy-scripts/config/webpack.environment.prod.js
  packages/cozy-scripts/config/webpack.target.mobile.js
  packages/cozy-scripts/config/webpack.vars.js
  packages/cozy-scripts/scripts/build.js
  packages/cozy-scripts/scripts/config.js
  packages/cozy-scripts/scripts/init.js
  packages/cozy-scripts/scripts/publish.js
  packages/cozy-scripts/scripts/release.js
  packages/cozy-scripts/scripts/start.js
  packages/cozy-scripts/scripts/test.js
  packages/cozy-scripts/scripts/watch.js
  packages/cozy-scripts/template-vue/app/jest.config.js
  packages/cozy-scripts/template/app/jest.config.js
  packages/cozy-scripts/test/lib/strategy.config.js
  packages/cozy-scripts/test/lib/test.config.js
  packages/cozy-scripts/test/scripts-vue.spec.js
  packages/cozy-scripts/test/scripts.spec.js
  packages/cozy-scripts/utils/paths.js
  packages/cozy-scripts/utils/runGlobalPackageCLI.js
  packages/create-cozy-app/create-cozy-app.js
  packages/create-cozy-app/index.js
  packages/create-cozy-app/test/mocks/mock-scripts/scripts/init.js
  yarn.lock
Labels: tag: chore

#830 Resolve src before node_modules
  packages/cozy-scripts/config/webpack.config.base.js
  packages/cozy-scripts/template-vue/app/jest.config.js
  packages/cozy-scripts/template/app/jest.config.js
  packages/cozy-scripts/test/__snapshots__/scripts-vue.spec.js.snap
  packages/cozy-scripts/test/__snapshots__/scripts.spec.js.snap
Labels: tag: enhancement
