Repository cozy/create-cozy-app, pull requests merged in 2018-03, with the labels that each got.

#330 Minor changes (manifests) :pencil2:
  packages/cozy-scripts-vanilla/template/manifest.webapp
  packages/cozy-scripts/template-vue/app/.travis.yml
  packages/cozy-scripts/template-vue/manifest.webapp
  packages/cozy-scripts/template-vue/package.json
  packages/cozy-scripts/template/app/.travis.yml
  packages/cozy-scripts/template/manifest.webapp
  packages/cozy-scripts/template/package.json
Labels: tag: enhancement

#335 Add app full name CLI question + remove the user website one
  packages/cozy-scripts-vanilla/scripts/init.js
  packages/cozy-scripts-vanilla/template/manifest.webapp
  packages/cozy-scripts-vanilla/test/scripts.spec.js
  packages/cozy-scripts/scripts/init.js
  packages/cozy-scripts/template-vue/manifest.webapp
  packages/cozy-scripts/template-vue/package.json
  packages/cozy-scripts/template/manifest.webapp
  packages/cozy-scripts/template/package.json
  packages/cozy-scripts/test/scripts-vue.spec.js
  packages/cozy-scripts/test/scripts.spec.js
Labels: tag: enhancement

#350 Update yarn version usage for Travis to 1.3.2
  .travis.yml
Labels: tag: chore

#348 Replace vue-test-utils by @vue/test-utils dependency
  packages/cozy-scripts/template-vue/app/test/app.spec.js
  packages/cozy-scripts/template-vue/app/test/ducks/components/helloViews.spec.js
  packages/cozy-scripts/template-vue/package.json
  packages/cozy-scripts/template-vue/yarn.lock
Labels: tag: chore

#352 Parallelize travis tests + remove yarn version freeze
  .travis.yml
Labels: tag: chore

#358 Fix typo, use --prefer-offline instead of wrong --prefer-online
  packages/cozy-scripts/scripts/init.js
  packages/cozy-scripts/test/scripts-vue.spec.js
  packages/cozy-scripts/test/scripts.spec.js
Labels: tag: bug

#362 Remove email CLI question + use default travis email to deploy
  packages/cozy-scripts/scripts/init.js
  packages/cozy-scripts/template-vue/package.json
  packages/cozy-scripts/template/package.json
  packages/cozy-scripts/test/scripts-vue.spec.js
  packages/cozy-scripts/test/scripts.spec.js
Labels: tag: enhancement

#370 Better default app name (capitalize + space)
  packages/cozy-scripts-vanilla/scripts/init.js
  packages/cozy-scripts/scripts/init.js
Labels: tag: enhancement

#381 Add `.npmignore` + update files in package.json for NPM packaging
  packages/cozy-scripts/.npmignore
  packages/cozy-scripts/package.json
Labels: tag: chore

#379 feat: drop standardjs in favor of prettier in eslint config
  packages/cozy-scripts/template-vue/app/.prettierrc
  packages/cozy-scripts/template-vue/package.json
  packages/cozy-scripts/template/app/.prettierrc
  packages/cozy-scripts/template/package.json
  packages/cozy-scripts/test/__snapshots__/scripts-vue.spec.js.snap
  packages/cozy-scripts/test/__snapshots__/scripts.spec.js.snap
  packages/eslint-config-cozy-app/index.js
  packages/eslint-config-cozy-app/package.json
  packages/eslint-config-cozy-app/yarn.lock
Labels: tag: breaking change

#389 Add eslint-config-cozy-app dependency to cozy-scripts
  packages/cozy-scripts/package.json
  packages/cozy-scripts/yarn.lock
Labels: tag: chore

#390 Remove unused cordova scripts from templates
  packages/cozy-scripts/template-vue/package.json
  packages/cozy-scripts/template/package.json
Labels: tag: enhancement

#391 Better handling NODE_ENV and build options with scripts/CLI
  packages/cozy-scripts/README.md
  packages/cozy-scripts/bin/cozy-scripts.js
  packages/cozy-scripts/scripts/build.js
  packages/cozy-scripts/scripts/config.js
  packages/cozy-scripts/scripts/standalone.js
  packages/cozy-scripts/scripts/watch.js
  packages/cozy-scripts/test/__snapshots__/scripts-vue.spec.js.snap
  packages/cozy-scripts/test/__snapshots__/scripts.spec.js.snap
  packages/cozy-scripts/test/scripts-vue.spec.js
  packages/cozy-scripts/test/scripts.spec.js
Labels: tag: feature

#395 Simplify yarn scripts and use new CLI options
  packages/cozy-scripts/template-vue/package.json
  packages/cozy-scripts/template/package.json
Labels: tag: enhancement

#396 Add bundle analyzer plugin behind --analyzer option
  packages/cozy-scripts/bin/cozy-scripts.js
  packages/cozy-scripts/config/webpack.bundle.default.js
  packages/cozy-scripts/config/webpack.bundle.vue.js
  packages/cozy-scripts/config/webpack.config.analyzer.js
  packages/cozy-scripts/config/webpack.vars.js
  packages/cozy-scripts/package.json
  packages/cozy-scripts/scripts/config.js
  packages/cozy-scripts/yarn.lock
Labels: tag: feature

#398 Add documentation about analyzer config file and option
  packages/cozy-scripts/README.md
  packages/cozy-scripts/docs/webpack-configs.md
Labels: tag: documentation

#399 Add `cozy-scripts test` command to run tests using Jest
  packages/cozy-scripts/README.md
  packages/cozy-scripts/bin/cozy-scripts.js
  packages/cozy-scripts/package.json
  packages/cozy-scripts/scripts/test.js
  packages/cozy-scripts/template-vue/package.json
  packages/cozy-scripts/template-vue/yarn.lock
  packages/cozy-scripts/template/package.json
  packages/cozy-scripts/template/yarn.lock
  packages/cozy-scripts/test/scripts-vue.spec.js
  packages/cozy-scripts/test/scripts.spec.js
  packages/cozy-scripts/utils/paths.js
  packages/cozy-scripts/yarn.lock
Labels: tag: feature

#397 Allow opinionated config for VueJS using `--vue`
  packages/cozy-scripts/README.md
  packages/cozy-scripts/bin/cozy-scripts.js
  packages/cozy-scripts/scripts/config.js
  packages/cozy-scripts/template-vue/app/app.config.js
  packages/cozy-scripts/template-vue/package.json
  packages/cozy-scripts/test/__snapshots__/scripts-vue.spec.js.snap
  packages/cozy-scripts/test/scripts-vue.spec.js
Labels: tag: enhancement

#401 Fix typo in .gitignore files
  packages/cozy-scripts/.gitignore
  packages/cozy-scripts/template-vue/app/gitignore
  packages/cozy-scripts/template/app/gitignore
Labels: tag: enhancement

#407 Fix and update cozy-scripts .gitignore and .npmignore
  packages/cozy-scripts/.gitignore
  packages/cozy-scripts/.npmignore
Labels: tag: chore

#409 Update cozy-scripts files property in package.json
  packages/cozy-scripts/package.json
Labels: tag: chore

#415 Disable proptypes checking in eslint config
  packages/eslint-config-cozy-app/index.js
Labels: tag: chore

#417 Fix minor lint issues in templates
  packages/cozy-scripts/template/app/src/components/App.jsx
Labels: tag: enhancement

#422 Add Travis CI documentation about automatic app build
  packages/cozy-scripts/docs/ci.md
  packages/cozy-scripts/docs/images/travis_ci_enabling.png
  packages/cozy-scripts/docs/images/travis_ci_settings.png
  packages/cozy-scripts/docs/images/travis_ci_token.png
Labels: tag: documentation

#428 chore: better clean tasks 📝
  packages/cozy-scripts/template-vue/package.json
  packages/cozy-scripts/template/package.json
Labels: tag: enhancement
