Repository cozy/create-cozy-app, pull requests merged in 2019-02, with the labels that each got.

#1091 Improve app travis config
  packages/cozy-scripts/template-vue/.travis.yml
  packages/cozy-scripts/template/.travis.yml
Labels: tag: enhancement

#1092 Remove hash usage for dev-server + provide contentBase option
  packages/cozy-scripts/scripts/start.js
Labels: tag: bug

#1094 Wrong test for some React components
  packages/cozy-scripts/template/app/test/components/Todos/__snapshots__/todoAdd.spec.js.snap
  packages/cozy-scripts/template/app/test/components/Todos/__snapshots__/todoRemoveButton.spec.js.snap
  packages/cozy-scripts/template/app/test/components/Todos/todoAdd.spec.js
  packages/cozy-scripts/template/app/test/components/Todos/todoRemoveButton.spec.js
Labels: tag: bug

#1069 Handle assets if public page + add favicons generator
  .travis.yml
  packages/cozy-scripts/config/webpack.bundle.default.js
  packages/cozy-scripts/config/webpack.bundle.preact.js
  packages/cozy-scripts/config/webpack.bundle.vue.js
  packages/cozy-scripts/config/webpack.config.assets.js
  packages/cozy-scripts/config/webpack.config.manifest.js
  packages/cozy-scripts/config/webpack.config.public.js
  packages/cozy-scripts/config/webpack.config.vendors.js
  packages/cozy-scripts/config/webpack.environment.dev.js
  packages/cozy-scripts/config/webpack.vars.js
  packages/cozy-scripts/package.json
  packages/cozy-scripts/template-vue/app/src/targets/assets/icon.svg
  packages/cozy-scripts/template-vue/app/src/targets/browser/index.ejs
  packages/cozy-scripts/template-vue/app/src/targets/browser/index.js
  packages/cozy-scripts/template/app/src/targets/assets/icon.svg
  packages/cozy-scripts/template/app/src/targets/browser/index.ejs
  packages/cozy-scripts/template/app/src/targets/browser/index.jsx
  packages/cozy-scripts/test/__snapshots__/scripts-vue.spec.js.snap
  packages/cozy-scripts/test/__snapshots__/scripts.spec.js.snap
  packages/cozy-scripts/test/__snapshots__/utils.spec.js.snap
  packages/cozy-scripts/utils/paths.js
  packages/cozy-scripts/yarn.lock
Labels: tag: breaking change

#1070 Use relative `node_modules` for webpack modules resolving
  packages/cozy-scripts/config/webpack.config.base.js
  packages/cozy-scripts/test/__snapshots__/scripts-vue.spec.js.snap
  packages/cozy-scripts/test/__snapshots__/scripts.spec.js.snap
  packages/cozy-scripts/test/__snapshots__/utils.spec.js.snap
  packages/cozy-scripts/test/scripts-vue.spec.js
  packages/cozy-scripts/utils/paths.js
Labels: tag: breaking change

#1106 Use only transpiled UI React components + upgrade cozy-ui to v19
  packages/cozy-scripts/config/webpack.config.cozy-ui.react.js
  packages/cozy-scripts/template-vue/app/src/styles/index.css
  packages/cozy-scripts/template-vue/app/src/styles/index.styl
  packages/cozy-scripts/template-vue/package.json
  packages/cozy-scripts/template-vue/yarn.lock
  packages/cozy-scripts/template/app/src/styles/index.css
  packages/cozy-scripts/template/app/src/styles/index.styl
  packages/cozy-scripts/template/app/test/components/Todos/__snapshots__/todoAdd.spec.js.snap
  packages/cozy-scripts/template/package.json
  packages/cozy-scripts/template/yarn.lock
  packages/cozy-scripts/test/__snapshots__/scripts-vue.spec.js.snap
  packages/cozy-scripts/test/__snapshots__/scripts.spec.js.snap
Labels: tag: breaking change

#1135 feat: Make the minification faster
  packages/cozy-scripts/config/webpack.environment.prod.js
  packages/cozy-scripts/docs/webpack-configs.md
  packages/cozy-scripts/test/__snapshots__/scripts-vue.spec.js.snap
  packages/cozy-scripts/test/__snapshots__/scripts.spec.js.snap
Labels: tag: enhancement
