Repository cozy/create-cozy-app, pull requests merged in 2019-01, with the labels that each got.

#1035 feat(cozy-scripts): Show regexp when using --show-config flag
  packages/cozy-scripts/bin/cozy-scripts.js
  packages/cozy-scripts/utils/regexpReplacer.js
Labels: tag: enhancement

#1036 Don't use hash for services files name
  packages/cozy-scripts/config/webpack.config.services.js
  packages/cozy-scripts/config/webpack.vars.js
Labels: tag: bug

#1039 Remove externals property for services build
  packages/cozy-scripts/config/webpack.config.services.js
  packages/cozy-scripts/test/__snapshots__/scripts.spec.js.snap
Labels: tag: bug

#1042 Handling public assets
  packages/cozy-scripts/config/webpack.config.public.js
  packages/cozy-scripts/config/webpack.environment.dev.js
  packages/cozy-scripts/config/webpack.vars.js
  packages/cozy-scripts/test/__snapshots__/scripts-vue.spec.js.snap
  packages/cozy-scripts/test/__snapshots__/scripts.spec.js.snap
Labels: tag: bug

#1052 Handle services by default + build public/intents only for browser target
  packages/cozy-scripts/config/webpack.bundle.default.js
  packages/cozy-scripts/config/webpack.bundle.preact.js
  packages/cozy-scripts/config/webpack.bundle.vue.js
  packages/cozy-scripts/config/webpack.config.intents.js
  packages/cozy-scripts/config/webpack.config.public.js
  packages/cozy-scripts/config/webpack.config.services.js
  packages/cozy-scripts/test/__snapshots__/scripts.spec.js.snap
Labels: tag: enhancement

#1028 feat(cozy-scripts): Handle flags at build time
  packages/cozy-scripts/config/webpack.config.base.js
  packages/cozy-scripts/config/webpack.vars.js
  packages/cozy-scripts/test/__snapshots__/scripts-vue.spec.js.snap
  packages/cozy-scripts/test/__snapshots__/scripts.spec.js.snap
Labels: tag: feature

#1054 fix: Downgrade webpack-dev-server to avoid host checking bug
  packages/cozy-scripts/package.json
  packages/cozy-scripts/yarn.lock
Labels: tag: bug

#1058 Add cli more options
  packages/cozy-scripts/bin/cozy-scripts.js
  packages/cozy-scripts/scripts/config.js
  packages/cozy-scripts/test/__snapshots__/cli.spec.js.snap
  packages/cozy-scripts/test/__snapshots__/scripts-vue.spec.js.snap
  packages/cozy-scripts/test/__snapshots__/scripts.spec.js.snap
  packages/cozy-scripts/test/cli.spec.js
  packages/cozy-scripts/test/scripts-vue.spec.js
  packages/cozy-scripts/test/scripts.spec.js
  packages/cozy-scripts/utils/constants.js
Labels: tag: enhancement

#1065 Make lint script failed correctly + fix vue app linting issues
  packages/cozy-scripts/scripts/lint.js
  packages/cozy-scripts/template-vue/app/src/components/App.vue
  packages/cozy-scripts/template-vue/app/src/components/Icon.vue
  packages/cozy-scripts/test/scripts-vue.spec.js
  packages/cozy-scripts/test/scripts.spec.js
Labels: tag: bug

#1067 Fix progress bar width overflow
  packages/cozy-scripts/config/webpack.config.progress.js
  packages/cozy-scripts/package.json
  packages/cozy-scripts/utils/progress.js
  packages/cozy-scripts/yarn.lock
Labels: tag: bug

#1073 Don't use absolute outputPath for file-loader
  packages/cozy-scripts/config/webpack.config.pictures.js
  packages/cozy-scripts/test/__snapshots__/scripts.spec.js.snap
Labels: tag: bug

#1078 docs: Document COZY_FLAGS
  packages/cozy-scripts/README.md
Labels: tag: documentation
